version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    environment:
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-mailparse
    steps:
      - run:
          name: Upgrade Docker CE
          command: |
            sudo apt-get update
            sudo apt-get install docker-ce=18.03.1~ce-0~ubuntu
      - run:
          name: Upgrade Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Build Docker images
          command: |
            docker-compose build --no-cache
      - run:
          name: Build RPM packages
          command: docker-compose up
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml pull
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos7bintray
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos6bintray
      - run:
          name: Upload Docker images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            sleep 30
            docker push aursu/peclbuild:7-mailparse
            docker push aursu/peclbuild:6-mailparse
  build5:
    machine:
      docker_layer_caching: true
    environment:
      BINTRAY_REPO: php5custom
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-mailparse
    steps:
      - run:
          name: Upgrade Docker CE
          command: |
            sudo apt-get update
            sudo apt-get install docker-ce=18.03.1~ce-0~ubuntu
      - run:
          name: Upgrade Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Build Docker images (PHP 5)
          command: |
            docker-compose -f docker-compose.php5.yml build --no-cache
      - run:
          name: Build RPM packages (PHP 5)
          command: docker-compose -f docker-compose.php5.yml up
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml pull
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos7bintray
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos6bintray
      - run:
          name: Upload Docker images (PHP 5)
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            sleep 30
            docker push aursu/peclbuild:7-mailparse-php5
            docker push aursu/peclbuild:6-mailparse-php5
workflows:
  version: 2
  mailparsebuild:
    jobs:
      - build
      - build5
